### PR TITLE
Feedback Page

### LINKED ISSUE #48: Fix: fix route issue in app.js

### LINKED ISSUE #49: UI/UX Feedback Page

### PR DESCRIPTION
**Pull request by nonsoo24**

### CODE REVIEW

**Comment by jothamardel** [comment]
@nonsoo24 you deleted the ReportAccident component from the routes.

**Review by Ose-Me — COMMENTED** [review]
the route for the report accident component is missing from the app.js file

**Review by jothamardel — CHANGES_REQUESTED** [review]
@nonsoo24 App.js is conflicting with the base branch because you committed one of the routes.

**Comment by nonsoo24** [comment]
@jothamardel and @Ose-Me  So sorry about that. I have resolved it and  push again

**Review by Ose-Me — APPROVED** [review]

**Review by jothamardel — APPROVED** [review]

**Review by Ose-Me — APPROVED** [review]

**Comment by Ose-Me** [comment]
@nonsoo24 naming conventions of components use camelCase

**Comment by nonsoo24** [comment]
@Ose-Me Noted. Although  we didn't agree on a naming convention at the onset

**Pull request merged**
